apiVersion: greatdb.com/v1alpha1
kind: GreatDBPaxos
metadata:
  name: greatdb-sample
spec:
  image: mysql:v8.0.26-05311142
  version: 8.0.26
  port: 3307
  service:
    type: NodePort
    readPort: 30021
    writePort: 30021
