apiVersion: greatdb.com/v1alpha1
kind: GreatDBBackupSchedule
metadata:
  name: nfs-backup-corn
spec:
  clusterName: greatdb-sample
  schedulers:
  - name: test1
    backupType: full
    backupResource: greatdb
    clean: "7d"
    schedule: "0 0 0 * * ?"
    selectStorage:
      type: nfs
