/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	greatdbv1alpha1 "greatdb-operator/pkg/apis/greatdb/v1alpha1"
	versioned "greatdb-operator/pkg/client/clientset/versioned"
	internalinterfaces "greatdb-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "greatdb-operator/pkg/client/listers/greatdb/v1alpha1"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// GreatDBPaxosInformer provides access to a shared informer and lister for
// GreatDBPaxoses.
type GreatDBPaxosInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.GreatDBPaxosLister
}

type greatDBPaxosInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewGreatDBPaxosInformer constructs a new informer for GreatDBPaxos type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewGreatDBPaxosInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredGreatDBPaxosInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredGreatDBPaxosInformer constructs a new informer for GreatDBPaxos type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredGreatDBPaxosInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GreatdbV1alpha1().GreatDBPaxoses(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GreatdbV1alpha1().GreatDBPaxoses(namespace).Watch(context.TODO(), options)
			},
		},
		&greatdbv1alpha1.GreatDBPaxos{},
		resyncPeriod,
		indexers,
	)
}

func (f *greatDBPaxosInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredGreatDBPaxosInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *greatDBPaxosInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&greatdbv1alpha1.GreatDBPaxos{}, f.defaultInformer)
}

func (f *greatDBPaxosInformer) Lister() v1alpha1.GreatDBPaxosLister {
	return v1alpha1.NewGreatDBPaxosLister(f.Informer().GetIndexer())
}
