/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	v1alpha1 "greatdb-operator/pkg/apis/greatdb/v1alpha1"
	scheme "greatdb-operator/pkg/client/clientset/versioned/scheme"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// GreatDBBackupRecordsGetter has a method to return a GreatDBBackupRecordInterface.
// A group's client should implement this interface.
type GreatDBBackupRecordsGetter interface {
	GreatDBBackupRecords(namespace string) GreatDBBackupRecordInterface
}

// GreatDBBackupRecordInterface has methods to work with GreatDBBackupRecord resources.
type GreatDBBackupRecordInterface interface {
	Create(ctx context.Context, greatDBBackupRecord *v1alpha1.GreatDBBackupRecord, opts v1.CreateOptions) (*v1alpha1.GreatDBBackupRecord, error)
	Update(ctx context.Context, greatDBBackupRecord *v1alpha1.GreatDBBackupRecord, opts v1.UpdateOptions) (*v1alpha1.GreatDBBackupRecord, error)
	UpdateStatus(ctx context.Context, greatDBBackupRecord *v1alpha1.GreatDBBackupRecord, opts v1.UpdateOptions) (*v1alpha1.GreatDBBackupRecord, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.GreatDBBackupRecord, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.GreatDBBackupRecordList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GreatDBBackupRecord, err error)
	GreatDBBackupRecordExpansion
}

// greatDBBackupRecords implements GreatDBBackupRecordInterface
type greatDBBackupRecords struct {
	client rest.Interface
	ns     string
}

// newGreatDBBackupRecords returns a GreatDBBackupRecords
func newGreatDBBackupRecords(c *GreatdbV1alpha1Client, namespace string) *greatDBBackupRecords {
	return &greatDBBackupRecords{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the greatDBBackupRecord, and returns the corresponding greatDBBackupRecord object, and an error if there is any.
func (c *greatDBBackupRecords) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.GreatDBBackupRecord, err error) {
	result = &v1alpha1.GreatDBBackupRecord{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("greatdbbackuprecords").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of GreatDBBackupRecords that match those selectors.
func (c *greatDBBackupRecords) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.GreatDBBackupRecordList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.GreatDBBackupRecordList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("greatdbbackuprecords").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested greatDBBackupRecords.
func (c *greatDBBackupRecords) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("greatdbbackuprecords").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a greatDBBackupRecord and creates it.  Returns the server's representation of the greatDBBackupRecord, and an error, if there is any.
func (c *greatDBBackupRecords) Create(ctx context.Context, greatDBBackupRecord *v1alpha1.GreatDBBackupRecord, opts v1.CreateOptions) (result *v1alpha1.GreatDBBackupRecord, err error) {
	result = &v1alpha1.GreatDBBackupRecord{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("greatdbbackuprecords").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(greatDBBackupRecord).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a greatDBBackupRecord and updates it. Returns the server's representation of the greatDBBackupRecord, and an error, if there is any.
func (c *greatDBBackupRecords) Update(ctx context.Context, greatDBBackupRecord *v1alpha1.GreatDBBackupRecord, opts v1.UpdateOptions) (result *v1alpha1.GreatDBBackupRecord, err error) {
	result = &v1alpha1.GreatDBBackupRecord{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("greatdbbackuprecords").
		Name(greatDBBackupRecord.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(greatDBBackupRecord).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *greatDBBackupRecords) UpdateStatus(ctx context.Context, greatDBBackupRecord *v1alpha1.GreatDBBackupRecord, opts v1.UpdateOptions) (result *v1alpha1.GreatDBBackupRecord, err error) {
	result = &v1alpha1.GreatDBBackupRecord{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("greatdbbackuprecords").
		Name(greatDBBackupRecord.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(greatDBBackupRecord).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the greatDBBackupRecord and deletes it. Returns an error if one occurs.
func (c *greatDBBackupRecords) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("greatdbbackuprecords").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *greatDBBackupRecords) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("greatdbbackuprecords").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched greatDBBackupRecord.
func (c *greatDBBackupRecords) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GreatDBBackupRecord, err error) {
	result = &v1alpha1.GreatDBBackupRecord{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("greatdbbackuprecords").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
