FROM kylin-10-sp1-aarch64:sys-20220630
LABEL MAINTAINER greatdb <greatdb.com>
COPY kylin_aarch64.repo /etc/yum.repo.d/
RUN curl -o /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-8.repo && \
     sed -i 's/$releasever/8/g' /etc/yum.repos.d/CentOS-Base.repo && \
     yum makecache && \
    yum install -y socat which sudo openssh-clients libaio numactl && \
    yum clean all && \
    rm -rf /var/cache && rm -rf /etc/yum.repos.d/*
RUN groupadd greatdb -g 1000 && \
    useradd -r -g greatdb -u 1000 -s /bin/false greatdb && \
    mkdir -p /greatdb/mysql /backup /xtrabackup_backupfiles  /home/greatdb && \
    chown -R greatdb:greatdb /opt /greatdb /greatdb/mysql /backup /xtrabackup_backupfiles /home/greatdb

#COPY --chown=greatdb:greatdb greatdb /opt/greatdb/
ADD --chown=greatdb:greatdb \
    mysql-8.0.26-linux-glibc2.17-aarch64.tar.gz \
    percona-xtrabackup.tar.gz \
    backup-recovery-tool.tar.gz \
    /opt/


COPY bin /usr/local/bin/
COPY --chown=greatdb:greatdb greatdb.cnf /etc/greatdb/greatdb.cnf
RUN chmod +x /usr/local/bin/greatdb-agent && \
    chmod +x /usr/local/bin/mc && \
    chmod +x /opt/backup-recovery-tool/binary_version/backup && \
    chmod +x /usr/local/bin/cluster-backup.sh

ENV PATH="${PATH}:/opt/mysql-8.0.26-linux-glibc2.17-aarch64/bin:/opt/percona-xtrabackup/bin:/opt/backup-recovery-tool/binary_version"

USER greatdb
ENTRYPOINT ["start-greatdb.sh"]