/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	v1alpha1 "greatdb-operator/pkg/apis/greatdb/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGreatDBBackupRecords implements GreatDBBackupRecordInterface
type FakeGreatDBBackupRecords struct {
	Fake *FakeGreatdbV1alpha1
	ns   string
}

var greatdbbackuprecordsResource = schema.GroupVersionResource{Group: "greatdb.com", Version: "v1alpha1", Resource: "greatdbbackuprecords"}

var greatdbbackuprecordsKind = schema.GroupVersionKind{Group: "greatdb.com", Version: "v1alpha1", Kind: "GreatDBBackupRecord"}

// Get takes name of the greatDBBackupRecord, and returns the corresponding greatDBBackupRecord object, and an error if there is any.
func (c *FakeGreatDBBackupRecords) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.GreatDBBackupRecord, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(greatdbbackuprecordsResource, c.ns, name), &v1alpha1.GreatDBBackupRecord{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GreatDBBackupRecord), err
}

// List takes label and field selectors, and returns the list of GreatDBBackupRecords that match those selectors.
func (c *FakeGreatDBBackupRecords) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.GreatDBBackupRecordList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(greatdbbackuprecordsResource, greatdbbackuprecordsKind, c.ns, opts), &v1alpha1.GreatDBBackupRecordList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.GreatDBBackupRecordList{ListMeta: obj.(*v1alpha1.GreatDBBackupRecordList).ListMeta}
	for _, item := range obj.(*v1alpha1.GreatDBBackupRecordList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested greatDBBackupRecords.
func (c *FakeGreatDBBackupRecords) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(greatdbbackuprecordsResource, c.ns, opts))

}

// Create takes the representation of a greatDBBackupRecord and creates it.  Returns the server's representation of the greatDBBackupRecord, and an error, if there is any.
func (c *FakeGreatDBBackupRecords) Create(ctx context.Context, greatDBBackupRecord *v1alpha1.GreatDBBackupRecord, opts v1.CreateOptions) (result *v1alpha1.GreatDBBackupRecord, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(greatdbbackuprecordsResource, c.ns, greatDBBackupRecord), &v1alpha1.GreatDBBackupRecord{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GreatDBBackupRecord), err
}

// Update takes the representation of a greatDBBackupRecord and updates it. Returns the server's representation of the greatDBBackupRecord, and an error, if there is any.
func (c *FakeGreatDBBackupRecords) Update(ctx context.Context, greatDBBackupRecord *v1alpha1.GreatDBBackupRecord, opts v1.UpdateOptions) (result *v1alpha1.GreatDBBackupRecord, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(greatdbbackuprecordsResource, c.ns, greatDBBackupRecord), &v1alpha1.GreatDBBackupRecord{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GreatDBBackupRecord), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeGreatDBBackupRecords) UpdateStatus(ctx context.Context, greatDBBackupRecord *v1alpha1.GreatDBBackupRecord, opts v1.UpdateOptions) (*v1alpha1.GreatDBBackupRecord, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(greatdbbackuprecordsResource, "status", c.ns, greatDBBackupRecord), &v1alpha1.GreatDBBackupRecord{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GreatDBBackupRecord), err
}

// Delete takes name of the greatDBBackupRecord and deletes it. Returns an error if one occurs.
func (c *FakeGreatDBBackupRecords) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(greatdbbackuprecordsResource, c.ns, name, opts), &v1alpha1.GreatDBBackupRecord{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGreatDBBackupRecords) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(greatdbbackuprecordsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.GreatDBBackupRecordList{})
	return err
}

// Patch applies the patch and returns the patched greatDBBackupRecord.
func (c *FakeGreatDBBackupRecords) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GreatDBBackupRecord, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(greatdbbackuprecordsResource, c.ns, name, pt, data, subresources...), &v1alpha1.GreatDBBackupRecord{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GreatDBBackupRecord), err
}
