apiVersion: greatdb.com/v1alpha1
kind: GreatDBPaxos
metadata:
  GUUuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuaskldfjmalksd mnname: greatdb-sample1
  namespace: wang
spec:
  backup:
    enable: true
    nfs:
      path: /nfs_file/greatdb_backup 
      server: 172.17.137.187  
    resources:
      limits:
        cpu: "2"
        memory: 2Gi
      requests:
        cpu: "1"
        memory: 1Gi
  clusterDomain: cluster.local
  delete: {}
  failOver:
    autoScaleiIn: false
    enable: true
    period: 10m
    maxInstance: 3
    maxUnavailable: 0
  image: registry.greatdb.com/operator/mysql-v8.0.26:latest
  imagePullPolicy: IfNotPresent
  instances: 3
  maintenanceMode: false
  pause:
    mode: ins
  podSecurityContext:
    fsGroup: 1000
    runAsUser: 1000
  port: 3306
  pvReclaimPolicy: Retain
  resources:
    limits:
      cpu: "2"
      memory: 2Gi
    requests:
      cpu: "2"
      memory: 2Gi
  restart:
    mode: cluster
    strategy: rolling
  scaling:
    scaleIn:
      strategy: fault
    scaleOut:
      source: clone
  service:
    readPort: 30020
    type: NodePort
    writePort: 30021
  upgradeStrategy: rollingUpgrade
  version: 8.0.26
  volumeClaimTemplates:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi
  dashboard:
    enable: true
    image: registry.greatdb.com/operator/greatdb-dashboard:latest
  logCollection:
    image: registry.greatdb.com/operator/promtail-v2.7.4:latest
