apiVersion: greatdb.com/v1alpha1
kind: GreatDBPaxos
metadata:
  name: greatdb-sample
spec:
  image: mysql:v8.0.26-05311142
  version: 8.0.26
  service:
    type: NodePort
    readPort: 30020
    writePort: 30021
  volumeClaimTemplates:
    resources:
      requests:
        storage: 11Gi
